- name: copy the repo 
  hosts: mongodb
  become: yes
  tasks: 
  - name: coping
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d
  - name: install mongodb
    ansible.builtin.yum:
      name: mongodb-org
      state: present
  - name: enable and start
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes
  - name: enable remote connection
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.0'
      replace: '0.0.0.0'
  - name: restart
    ansible.builtin.service:
      name: mongod
      state: restarted
